"""baseline: existing schema

Revision ID: b5b951e6d6e1
Revises: 
Create Date: 2026-09-30 11:35:45.572167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b951e6d6e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('mood_tags', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('songs', sa.Column('bpm', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'bpm')
    op.drop_column('songs', 'mood_tags')
    op.drop_column('songs', 'genre')
    # ### end Alembic commands ###
