"""swap song audio_url for audio_key (private B2 storage)

Revision ID: d909ae42e294
Revises: b5b951e6d6e1
Create Date: 2026-10-06 12:33:00.260588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd909ae42e294'
down_revision: Union[str, Sequence[str], None] = 'b5b951e6d6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('audio_key', sa.String(), nullable=True))
    op.drop_column('songs', 'audio_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('songs', 'audio_key')
    # ### end Alembic commands ###
